# Final Project
# Akio Pancho, Partner: Jonathan Rodriguez, Title: The Population Transformation, Prof:Hayes
# TODO: A program that gives statistics related to population birth rates of the countries of low birth rate(China, South Korea, Japan) and countries with high birth rate(Niger, Somalia, DRCongo.The 6 statistics include: birth rates, life expectancy, death rates, and population pyramids which will be Animated...Citations: We are using statistics from the World Bank website
''' Our Program has 5 parts
1.)Welcome Screen: (Event Driven Program that will bring user to next part) Akio 
2.)Background info: (Lots of background info on Population Growth Rates, some stats, slideshow)
3.)4 Statistics Page:(User Has to Pick 1 of 4 Graphs Displayed on Screen to get info) 
4.)Chosen Statistical Graph:(User can have a better sense of the graph/info of specific statistic) Jonathan
5.)End Screen: (End screen. restart the program)'''
#Write your code here#
#CODE BELOW JUST PREPARES THE SCREEN AND IMPORTS STUFF
import turtle
import random
import turtle
import matplotlib.pyplot as plt
import time
turtle.tracer(False)
#cleans data from a file
def data_cleanse(lst):
    for i in range(len(lst)):
        if lst[i] == '<1\n' or lst[i] == '<1':
            lst[i] = 0
        else:
            lst[i] = int(float(lst[i]))
#opens file and cleans the data
def data_open(lst):
    file_open = open(lst)
    file_list = file_open.readlines()
    data_cleanse(file_list)
    return file_list
#random function
def rando(a,b):
    r = random.randint(a,b)
    return r
#Creates the graphs(birth, death, and life rates)
new1 = data_open('2china.txt')
new2 = data_open('2japan.txt')
new3 = data_open('2southkorea.txt')
new4 = data_open('2niger.txt')
new5 = data_open('2somalia.txt')
new6 = data_open('2congo.txt')
plt.plot(new1, 'b-')
plt.plot(new2, 'g-')
plt.plot(new3, 'r-')
plt.plot(new4, 'c-')
plt.plot(new5, 'm-')
plt.plot(new6, 'y-')
plt.xlabel('Year')
plt.ylabel('Birth')
plt.title('Birth Rate Of 6 Countries')
plt.legend(['China', 'Japan', 'South Korea', 'Niger', 'Somalia', 'DR Congo'])
Xticks = [0, 10, 20, 30, 40, 50, 60]
Years = ['1960', '1970', '1980', '1990', '2000', '2010', '2020']
plt.xticks(Xticks, Years)
# plt.savefig('birthrates.png')
s = turtle.getscreen()
s.setup(width = 800, height = 600)
turtle.hideturtle()
#imporant backgrounds
turtle.addshape('screen.gif')
turtle.addshape('dark.gif')
turtle.addshape('light.gif')
#gets the buttons needed for menu screen
turtle.addshape('br.gif')
turtle.addshape('dr.gif')
turtle.addshape('le.gif')
turtle.addshape('pp.gif')
turtle.addshape('words.gif')
#gets the graph of 3 of the categories
turtle.addshape('birthrates.gif')
turtle.addshape('deathrate.gif')
turtle.addshape('lifeexpectancy.gif')
#gets bottons for menu screen
turtle.addshape('china_button.gif')
turtle.addshape('japan_button.gif')
turtle.addshape('korea_button.gif')
turtle.addshape('niger_button.gif')
turtle.addshape('somalia_button.gif')
turtle.addshape('congo_button.gif')

'''pyramid and animating letters Functions'''########################################################
q = turtle.Turtle()
q.hideturtle()
q.penup()
q.pencolor('yellow')
# no more x:50, y:90,....xLETTERSspace:5, yLINESspace:10........SPACEWORDS: 50
# size:600, y cors only be fit screen -> |290-200|190-100|90-0|-3--93|-103-193|-203--293|
#MAX LETTERS 
#size:800, x cors #1 -> |-390--340|-335--285|-280--230|-225--175|-170--120|-115--65|-60--10|
#size:800, x cors #2 -> |-5-45|50-100|105-155|160-210|215-265|270-320|325-375|
def square(num):
    q.pendown()
    for sides in range(4):
        q.forward(num)
        q.right(90)
def clear():
    q.clear()
def way(num):
    q.setheading(num)
turtle.tracer(True)
xcor=[-390, -335, -280, -225, -170, -115, -60, -5, 50, 105, 160, 215, 270, 325] #14
ycor = [290, 190, 90, -3, -103, -203] #6
def cl(x,y):
    q.penup()
    q.goto(xcor[x],ycor[y])
    q.setheading(270)
def aa():
    q.forward(90)
    q.setheading(75)
    q.pendown()
    q.forward(90)
    q.setheading(287)
    q.forward(90)
    q.backward(25)
    q.setheading(180)
    q.forward(35)
    q.penup()
    q.backward(40)
def bb():
    q.pendown()
    q.forward(90)
    q.setheading(0)
    q.forward(30) #15
    q.setheading(90) 
    q.forward(5) #85
    q.setheading(0) 
    q.forward(20) #5
    q.setheading(90)
    q.forward(15) #70
    #draws bottom square hole
    q.penup()
    q.setheading(180)
    q.forward(15)########
    square(10)
    q.penup()
    q.backward(15)
    q.setheading(90)
    #back to drawing
    q.pendown()
    q.forward(25) #55
    q.setheading(180)
    q.forward(20)
    q.setheading(90)
    q.forward(5) #45
    q.setheading(0)
    q.forward(20)
    q.setheading(90)
    q.forward(15) #30
    #draws bottom square hole
    q.penup()
    q.setheading(180)
    q.forward(15)########
    square(10)
    q.penup()
    q.backward(15)
    #back to drawing
    q.pendown()
    q.setheading(90)
    q.forward(20)
    q.setheading(180)
    q.forward(20)
    q.setheading(90)
    q.forward(5)
    q.setheading(180)
    q.forward(30)
    q.hideturtle()
def cc():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(50)
    q.setheading(270)
    q.forward(90)
    q.setheading(0)
    q.forward(50)
def dd():
    q.pendown()
    q.forward(90)
    q.setheading(0)
    q.forward(40)
    q.setheading(90)
    q.forward(10)
    q.setheading(0)
    q.forward(10)
    q.setheading(90)
    q.forward(20)
    #Creates hole in middle for D
    q.penup()
    q.setheading(180)
    q.forward(12)
    square(25)
    q.penup()
    q.backward(12)
    q.setheading(90)
    #back to drawing
    q.pendown()
    q.forward(50)
    q.setheading(180)
    q.forward(10)
    q.setheading(90)
    q.forward(10)
    q.setheading(180)
    q.forward(40)
def ee():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(50)
    q.setheading(270)
    q.forward(45)
    q.setheading(0)
    q.forward(50)
    q.backward(50)
    q.setheading(270)
    q.forward(45)
    q.setheading(0)
    q.forward(50)
def ff():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(50)
    q.setheading(270)
    q.forward(45)
    q.setheading(0)
    q.forward(50)
    q.backward(50)
    q.setheading(270)
    q.forward(45)
def gg():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(50)
    q.setheading(270)
    q.forward(90)
    q.setheading(0)
    q.forward(50)
    q.setheading(90)
    q.forward(40)
    q.setheading(180)
    q.forward(30)
def hh():
    q.pendown()
    q.forward(90)
    q.backward(45)
    q.setheading(0)
    q.forward(50)
    q.setheading(90)
    q.forward(45)
    q.setheading(270)
    q.forward(90)
def ii():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(25)
    q.setheading(270)
    q.forward(90)
    q.setheading(0)
    q.forward(25)
    q.backward(50)
def jj():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(20)
    q.setheading(270)
    q.forward(90)
    q.setheading(180)
    q.forward(25)
    q.setheading(90)
    q.forward(30)
    q.setheading(0)
    q.forward(3)
def kk():
    q.pendown()
    q.forward(90)
    q.backward(45)
    q.setheading(40)
    q.forward(65)
    q.backward(65)
    q.setheading(320)
    q.forward(65)
def ll():
    q.pendown()
    q.forward(90)
    q.setheading(0)
    q.forward(50)
def mm():
    q.pendown()
    q.forward(90)
    q.backward(90)
    q.setheading(0)
    q.forward(15)
    q.setheading(270)
    q.forward(60)
    q.setheading(0)
    q.forward(20)
    q.setheading(90)
    q.forward(60)
    q.setheading(0)
    q.forward(15)
    q.setheading(270)
    q.forward(90)
def nn():
    q.pendown()
    q.forward(90)
    q.backward(90)
    q.setheading(300)
    q.forward(103)
    q.setheading(90)
    q.forward(90)
def oo():
    q.pendown()
    q.forward(90)
    q.left(90)
    q.forward(50)
    q.left(90)
    q.forward(90)
    q.left(90)
    q.forward(50)
def pp():
    q.pendown()
    q.forward(90)
    q.backward(90)
    q.setheading(0)
    q.forward(50)
    q.setheading(270)
    q.forward(40)
    q.setheading(180)
    q.forward(50)
def qq():
    q.pendown()
    q.forward(90)
    q.left(90)
    q.forward(50)
    q.left(90)
    q.forward(90)
    q.left(90)
    q.forward(50)
    #backwards
    q.backward(50)
    q.setheading(270)
    q.forward(90)
    q.setheading(135)
    #back to code
    q.backward(3)
    q.forward(35)
def rr():
    q.pendown()
    q.forward(90)
    q.backward(90)
    q.setheading(0)
    q.forward(50)
    q.right(90)
    q.forward(40)
    q.right(90)
    q.forward(50)
    q.setheading(315)
    q.forward(70)
def ss():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(50)
    q.setheading(270)
    q.forward(45)
    q.setheading(0)
    q.forward(50)
    q.setheading(270)
    q.forward(45)
    q.setheading(180)
    q.forward(50)
def tt():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.backward(25)
    q.setheading(270)
    q.forward(90)
def uu():
    q.pendown()
    q.forward(90)
    q.setheading(0)
    q.forward(50)
    q.setheading(90)
    q.forward(90)
def vv():
    q.pendown()
    q.setheading(287)
    q.forward(90)
    q.setheading(75)
    q.forward(90)
def ww():
    q.pendown()
    q.forward(90)
    q.setheading(0)
    q.forward(15)
    q.setheading(90)
    q.forward(45)
    q.setheading(0)
    q.forward(20)
    q.setheading(270)
    q.forward(45)
    q.setheading(0)
    q.forward(15)
    q.setheading(90)
    q.forward(90)
def xx():
    q.pendown()
    q.setheading(300)
    q.forward(100)
    q.backward(100)
    #goes to other side
    q.penup()
    q.setheading(0)
    q.forward(50)
    q.setheading(240)
    q.pendown()
    #back to code
    q.forward(100)
def yy():
    q.pendown()
    q.forward(45)
    q.setheading(0)
    q.forward(25)
    q.setheading(270)
    q.forward(45)
    q.backward(45)
    q.setheading(0)
    q.forward(25)
    q.setheading(90)
    q.forward(45)
def zz():
    q.pendown()
    q.setheading(0)
    q.forward(50)
    q.setheading(240)
    q.forward(100)
    q.setheading(0)
    q.forward(50)
def space():
    q.penup()
    q.setheading(0)
    q.forward(50)
#creates sentence
def sentence(q):
    #x max len:14 (13), y max len:6 (5), max char for each page:84
    char=0
    x=0
    y=0
    for i in range(len(q)):
        q = q.lower()
        #if char>84, page is cleared and text continues
        char+=1
        if char>=84:
            clear()
            char=0
            x = 0
            y = 0
        if x >= 14:
            x=0
            y+=1
        #calls the function cl for position of x and y
        cl(x,y)
        #once position is set, this checks the char and outputs it
        if q[i] == 'a':
            aa()
        elif q[i] == 'b':
            bb()
        elif q[i] == 'c':
            cc()
        elif q[i] == 'd':
            dd()
        elif q[i] == 'e':
            ee()
        elif q[i] == 'f':
            ff()
        elif q[i] == 'g':
            gg()
        elif q[i] == 'h':
            hh()
        elif q[i] == 'i':
            ii()
        elif q[i] == 'j':
            jj()
        elif q[i] == 'k':
            kk()
        elif q[i] == 'l':
            ll()
        elif q[i] == 'm':
            mm()
        elif q[i] == 'n':
            nn()
        elif q[i] == 'o':
            oo()
        elif q[i] == 'p':
            pp()
        elif q[i] == 'q':
            qq()
        elif q[i] == 'r':
            rr()
        elif q[i] == 's':
            ss()
        elif q[i] == 't':
            tt()
        elif q[i] == 'u':
            uu()
        elif q[i] == 'v':
            vv()
        elif q[i] == 'w':
            ww()
        elif q[i] == 'x':
            xx()
        elif q[i] == 'y':
            yy()
        elif q[i] == 'z':
            zz()
        elif q[i] == ' ':
            space()

        x+=1


#########################Jonathan's Population Pyramid Function
g = turtle.Turtle()
g.hideturtle()
g.speed(10000)

#Global Variables
#Space between y-ticks
h = 15

g.penup()
g.goto(-395,300)

def axis_lines():
    x_end,y_end = g.pos()

    g.right(90)
    g.forward(10)

    g.pendown()
    g.left(90)
    g.forward(50)
    x_top,y_top = g.pos()

    #Makes axis lines

    #y-axis
    g.right(90)
    g.forward(580)
    g.forward(-70)
    x_bot,y_bot = g.pos()

    #x-axis
    g.right(90)
    g.forward(40)
    g.forward(-770)

    g.penup()
    g.goto(x_top,y_top)
    g.right(-90)
    g.forward(10)
    g.left(-90)
    g.forward(40)

    turtle.tracer(True)
    time.sleep(2)
    turtle.tracer(False)
    return x_bot,y_bot

#Makes y ticks on y-axis
def yticks():
    #y-ticks
    #100
    #1
    g.pendown()
    g.left(90)
    g.forward(10)
    #0
    g.penup()
    g.left(90)
    g.forward(5)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    #0
    g.penup()
    g.right(180)
    g.forward(10)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #95
    #9
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    x1,y1 = g.pos()
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.penup()
    g.goto(x1,y1)
    g.pendown()
    g.right(180)
    g.forward(10)
    x1,y1 = g.pos()
    #5
    g.penup()
    g.left(90)
    g.forward(5)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #90
    g.penup()
    g.goto(x1,y1)
    g.forward(-5)
    g.right(90)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    x1,y1 = g.pos()
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.penup()
    g.goto(x1,y1)
    g.pendown()
    g.right(180)
    g.forward(10)
    #0
    g.penup()
    g.left(90)
    g.forward(5)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #85
    #8
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.penup()
    g.forward(-5)
    g.right(90)
    g.forward(5)
    #5
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #80
    #8
    g.penup()
    g.right(90)
    g.forward(h)
    g.right(90)
    g.forward(15)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.penup()
    g.forward(-5)
    g.right(90)
    g.forward(5)
    #0
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #75
    #7
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h)
    x1,y1 = g.pos()
    g.forward(10)
    x2,y2 = g.pos()
    g.goto(x1,y1)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.goto(x2,y2)
    g.penup()
    g.forward(10)
    #5
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #70
    #7
    g.penup()
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(15)
    g.left(90)
    g.forward(h)
    g.penup()
    x1,y1 = g.pos()
    g.forward(10)
    x2,y2 = g.pos()
    g.goto(x1,y1)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.goto(x2,y2)
    g.penup()
    g.forward(10)
    #0
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #65
    #6
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.forward(-5)
    g.right(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.penup()
    g.forward(5)
    g.left(90)
    g.forward(10)
    #5
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #60
    #6
    g.penup()
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(15)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.forward(-5)
    g.right(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.penup()
    g.forward(5)
    g.left(90)
    g.forward(10)
    #0
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #55
    #5
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h+10)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(5)
    #5
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #50
    #5
    g.penup()
    g.forward(-15)
    g.right(90)
    g.forward(10)
    g.forward(h+10)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    #0
    g.penup()
    g.right(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #45
    #4
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.forward(-10)
    #5
    g.penup()
    g.right(90)
    g.forward(5)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #40
    #4
    g.penup()
    g.forward(-15)
    g.right(90)
    g.forward(10)
    g.forward(h)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.forward(-10)
    #0
    g.penup()
    g.right(90)
    g.forward(5)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #35
    #3
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.forward(-5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    #5
    g.penup()
    g.forward(-10)
    g.left(180)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #30
    #3
    g.penup()
    g.forward(-15)
    g.right(90)
    g.forward(10)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.forward(-5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    #0
    g.penup()
    g.right(180)
    g.forward(10)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #25
    #2
    g.penup()
    g.forward(10)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    #5
    g.penup()
    g.forward(5)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #20
    #2
    g.penup()
    g.forward(-15)
    g.right(90)
    g.forward(10)
    g.forward(h)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    #0
    g.penup()
    g.forward(5)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #15
    #1
    g.penup()
    g.forward(5)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.forward(10)
    g.penup()
    #5
    g.left(90)
    g.forward(5)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

    #10
    #1
    g.penup()
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(10)
    g.left(90)
    g.forward(h)
    g.pendown()
    g.forward(10)
    #0
    g.penup()
    g.left(90)
    g.forward(5)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)

    #5
    #5
    g.penup()
    g.left(90)
    g.forward(10)
    g.forward(h)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)

#Makes x ticks on x-axis
def xticks(x_bot,y_bot):
    #x-ticks
    #Space between x-ticks
    w = 62

    g.penup()
    g.goto(x_bot,y_bot)
    g.forward(w)
    g.right(90)
    g.pendown()
    g.forward(20)

    #8
    g.penup()
    g.forward(15)
    g.right(90)
    g.forward(5)
    g.right(180)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.penup()
    g.forward(-5)
    g.right(90)
    g.forward(5)

    #%
    g.penup()
    g.forward(-25)
    xp,yp = g.pos()

    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)

    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*2)
    g.right(90)
    g.pendown()
    g.forward(20)

    #6
    g.penup()
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(180)
    g.pendown()
    g.forward(5)
    g.forward(-5)
    g.right(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.penup()
    g.forward(5)
    g.left(90)
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(-5)
    g.right(180)
    #%
    g.forward(-25)
    xp,yp = g.pos()
    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)


    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*3)
    g.right(90)
    g.pendown()
    g.forward(20)

    #4
    g.penup()
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.forward(-10)
    #%
    g.penup()
    g.forward(10)
    g.right(90)
    g.forward(-10)
    g.right(180)
    g.forward(-25)
    xp,yp = g.pos()
    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)


    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*4)
    g.right(90)
    g.pendown()
    g.forward(20)

    #2
    g.penup()
    g.forward(15)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    #%
    g.penup()
    g.forward(5)
    g.forward(-25)
    xp,yp = g.pos()
    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)


    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*5)
    x,y = g.pos()
    g.right(90)
    g.pendown()
    g.forward(20)

    #0
    g.penup()
    g.forward(15)
    g.right(90)
    g.forward(5)
    g.right(180)
    g.pendown()
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.right(90)
    g.forward(5)
    #%
    g.penup()
    g.forward(5)
    g.right(90)
    g.forward(10)
    g.left(90)
    g.forward(-25)
    xp,yp = g.pos()
    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)


    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*6)
    g.right(90)
    g.pendown()
    g.forward(20)

    #2
    g.penup()
    g.forward(15)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.pendown()
    g.left(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    #%
    g.penup()
    g.forward(5)
    g.forward(-25)
    xp,yp = g.pos()
    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)


    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*7)
    g.right(90)
    g.pendown()
    g.forward(20)

    #4
    g.penup()
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.forward(-10)
    #%
    g.penup()
    g.forward(10)
    g.right(90)
    g.forward(-10)
    g.right(180)
    g.forward(-25)
    xp,yp = g.pos()
    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)


    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*8)
    g.right(90)
    g.pendown()
    g.forward(20)

    #6
    g.penup()
    g.forward(5)
    g.right(90)
    g.forward(5)
    g.right(180)
    g.pendown()
    g.forward(5)
    g.forward(-5)
    g.right(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.penup()
    g.forward(5)
    g.left(90)
    g.left(90)
    g.forward(10)
    g.right(90)
    g.forward(-5)
    g.right(180)
    #%
    g.forward(-25)
    xp,yp = g.pos()
    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)


    g.penup()
    g.goto(x_bot,y_bot)
    g.left(90)
    g.forward(w*9)
    g.right(90)
    g.pendown()
    g.forward(20)

    #8
    g.penup()
    g.forward(15)
    g.right(90)
    g.forward(5)
    g.right(180)
    g.left(90)
    g.pendown()
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(10)
    g.left(90)
    g.forward(5)
    g.left(90)
    g.forward(5)
    g.penup()
    g.forward(-5)
    g.right(90)
    g.forward(5)

    #%
    g.penup()
    g.forward(-25)
    xp,yp = g.pos()

    g.forward(10)
    g.left(90)
    g.forward(10)
    g.pendown()
    g.goto(xp,yp)
    g.penup()
    g.forward(-3)
    g.right(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()
    g.goto(xp,yp)
    g.forward(3)
    g.left(90)
    g.forward(8)
    g.pendown()
    g.circle(3)
    g.penup()

    return x,y

#Make a population pyramid 
def pyramid(x,y,list_m,list_f):
    #Space between blocks
    h = 24
    fill1 = 'orange red'
    fill2 = 'dodger blue'

    g.goto(x,y)
    g.pendown()
    g.pencolor('white')
    g.left(90)

    for i in range(len(list_m)):
        #F
        g.fillcolor(fill2)
        g.begin_fill()
        g.forward(x*list_m[i])
        g.left(90)
        g.forward(h)
        g.left(90)
        g.forward(x*list_m[i])
        g.end_fill()
        #M
        g.fillcolor(fill1)
        g.begin_fill()
        g.forward(x*list_f[i])
        g.left(90)
        g.forward(h)
        g.left(90)
        g.forward(x*list_f[i])
        g.end_fill()
        g.left(90)
        g.forward(h)
        g.right(90)

        turtle.tracer(True)
        time.sleep(0.5)
        turtle.tracer(False)


#takes user to end screen EXCEPT FOR pyramids 
def end_dark(x,y):

        b = turtle.Turtle()
        b.penup()
        b.showturtle()
        b.goto(0,0)
        b.shape('dark.gif')
        #text object
        t_textt = turtle.Turtle()
        t_textt.pencolor('yellow')
        t_textt.hideturtle()
        t_textt.penup()
        t_textt.goto(0,0)
        t_textt.write('End Screen. Restart program to go to menu', False, align="center", font=("Playfair", 20, "normal"))
        # time.sleep(5)
#create population pyramids backgrounds
def the_pyramid_background():
    bground = turtle.Turtle()
    bground.penup()
    bground.showturtle()
    bground.goto(0,0)
    bground.shape('light.gif')

#FOR POPULATION PYRAMIDS PAGE, this is for telling user to click to go back
def pp_back():
    b = turtle.Turtle()
    b.penup()
    b.hideturtle()
    b.shape('light.gif')

    txt = turtle.Turtle()
    txt.pencolor('black')
    txt.hideturtle()
    txt.penup()
    txt.goto(180,255)
    txt.write('Restart program to go back to menu', False, align="center", font=("Playfair", 16, "normal"))

    b.onclick(end_dark)


'''background info'''##################################################
def word_animation(x,y):
    # turtle.Screen().bgcolor('black')
    q.hideturtle()
    q.speed(10000)
    #SAY WHATEVER YOU WANT
    sentence('There has been an explosion of babies in  the past  two centuries')
    time.sleep(2)
    clear()
    sentence('In the dynamic landscape  of global       demographic   trends')
    time.sleep(2)
    clear()
    sentence('Studying      population    growth rates  is important  for knowing   the future')
    time.sleep(2)
    clear()
    sentence('the world     population    just passed   eight billion according to the world bank')
    time.sleep(2)
    clear()
    sentence('Today we will focus on')
    time.sleep(2)
    clear()
    sentence('countries with low birth rates like China    Japan   and South Korea')
    time.sleep(2)
    clear()
    sentence('and countries with high birth rates like Niger   Somalia    and the Democratic Republic of Congo')
    time.sleep(2)
    clear()
    sentence('the statistics will be based on factors   that influence growth rates like')
    time.sleep(2)
    clear()
    sentence('birth rates')
    time.sleep(1)
    clear()
    sentence('death rates')
    time.sleep(1)
    clear()
    sentence('life          expectancy')
    time.sleep(1)
    clear()
    sentence('and population pyramids')
    time.sleep(1)
    clear()
    end_dark(x,y)

'''MENU'''############################################
def menu():
    turtle.tracer(True)

    # outputs the name of country population pyramid
    text = turtle.Turtle()
    text.pencolor('black')
    text.hideturtle()
    text.penup()

    back = turtle.Turtle()
    back.goto(0,0)
    back.shape('dark.gif')

    text_top = turtle.Turtle()
    text_top.pencolor('yellow')
    text_top.hideturtle()
    text_top.penup()
    text_top.goto(0,250)
    text_top.write('Please choose an option (the last option is really cool)', False, align="center", font=("Playfair", 20, "normal"))

    #functions for making population pyramids of specified country
    def make_pyramid_china(x,y):
        #creates the white background
        the_pyramid_background()
        #sets up turtle to make pyramid
        x_bot,y_bot = axis_lines()
        yticks()
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        x,y = xticks(x_bot,y_bot)
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        #displays text
        text.goto(0,-285)
        text.write('Population Pyramid of China', False, align="center", font=("Playfair", 10, "normal"))
        #makes the population pyramid
        pyramid(x,y,[2.3,3.3,3.4,3.1,3.0,3.2,4.1,4.1,3.6,3.5,4.3,4.0,2.6,2.5,1.9,1.1,0.6,0.3,0.1,0.1,0.1],[2.0,2.9,2.9,2.6,2.6,2.8,3.7,3.8,3.4,3.4,4.3,4.0,2.7,2.8,2.2,1.3,0.8,0.5,0.2,0.1,0.1])
        pp_back()
    def make_pyramid_japan(x,y):
        #creates the white background
        the_pyramid_background()
        #sets up turtle to make pyramid
        x_bot,y_bot = axis_lines()
        yticks()
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        x,y = xticks(x_bot,y_bot)
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        #displays text
        text.goto(0,-285)
        text.write('Population Pyramid of Japan', False, align="center", font=("Playfair", 10, "normal"))
        #makes the population pyramid
        pyramid(x,y,[1.7,2.0,2.2,2.3,2.5,2.5,2.6,2.8,3.1,3.7,3.8,3.3,3.0,2.9,3.4,2.8,2.1,1.3,0.5,0.1,0.1],[1.6,1.9,2.1,2.2,2.4,2.4,2.5,2.7,3.0,3.6,3.7,3.3,3.0,3.0,3.8,3.4,2.9,2.1,1.2,0.5,0.1])
        pp_back()
    def make_pyramid_korea(x,y):
        #creates the white background
        the_pyramid_background()
        #sets up turtle to make pyramid
        x_bot,y_bot = axis_lines()
        yticks()
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        x,y = xticks(x_bot,y_bot)
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        #displays text
        text.goto(0,-285)
        text.write('Population Pyramid of South Korea', False, align="center", font=("Playfair", 10, "normal"))
        #makes the population pyramid
        pyramid(x,y,[1.5,2.0,2.3,2.3,2.9,3.6,3.6,3.4,4.0,3.9,4.4,4.0,4.0,3.1,2.0,1.4,1.0,0.4,0.1,0.1,0.1],[1.4,1.9,2.2,2.1,2.7,3.2,3.2,3.1,3.8,3.7,4.3,4.0,4.1,3.3,2.3,1.8,1.5,0.9,0.4,0.1,0.1])
        pp_back()
    def make_pyramid_niger(x,y):
        #creates the white background
        the_pyramid_background()
        #sets up turtle to make pyramid
        x_bot,y_bot = axis_lines()
        yticks()
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        x,y = xticks(x_bot,y_bot)
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        #displays text
        text.goto(0,-285)
        text.write('Population Pyramid of Niger', False, align="center", font=("Playfair", 10, "normal"))
        #makes the population pyramid
        pyramid(x,y,[8.9,8.1,6.7,5.5,4.4,3.5,2.8,2.3,1.9,1.5,1.2,1.0,0.8,0.5,0.3,0.2,0.1,0.1,0.1,0.1,0.0],[8.9,7.9,6.5,5.3,4.3,3.4,2.6,2.2,1.8,1.4,1.2,1.0,0.8,0.6,0.4,0.2,0.1,0.1,0.1,0.1,0.0])
        pp_back()
    def make_pyramid_somalia(x,y):
        #creates the white background
        the_pyramid_background()
        #sets up turtle to make pyramid
        x_bot,y_bot = axis_lines()
        yticks()
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        x,y = xticks(x_bot,y_bot)
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        #displays text
        text.goto(0,-285)
        text.write('Population Pyramid of Somalia', False, align="center", font=("Playfair", 10, "normal"))
        #makes the population pyramid
        pyramid(x,y,[8.9,7.9,6.6,5.5,4.6,3.7,2.7,2.4,1.9,1.5,1.2,0.9,0.7,0.5,0.3,0.2,0.1,0.1,0.1,0.1,0.1],[8.9,7.7,6.4,5.4,4.5,3.7,2.7,2.4,2.0,1.5,1.3,1.0,0.8,0.6,0.4,0.2,0.1,0.1,0.1,0.1,0.1])
        pp_back()
    def make_pyramid_congo(x,y):
        #creates the white background
        the_pyramid_background()
        #sets up turtle to make pyramid
        x_bot,y_bot = axis_lines()
        yticks()
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        x,y = xticks(x_bot,y_bot)
        turtle.tracer(True)
        time.sleep(2)
        turtle.tracer(False)
        #displays text
        text.goto(0,-285)
        text.write('Population Pyramid of Democratic Republic of Congo', False, align="center", font=("Playfair", 10, "normal"))
        #makes the population pyramid
        pyramid(x,y,[8.9,7.7,6.4,5.2,4.3,3.6,3.0,2.4,1.9,1.5,1.3,1.0,0.8,0.6,0.4,0.2,0.1,0.1,0.1,0.1,0.1],[8.9,7.7,6.4,5.2,4.3,3.7,3.0,2.5,2.0,1.6,1.4,1.1,0.9,0.6,0.4,0.3,0.1,0.1,0.1,0.1,0.1,0.1])
        pp_back()

    #words animation option
    wo = turtle.Turtle()
    wo.penup()
    wo.showturtle()
    wo.goto(0,0)
    wo.shape('words.gif')
    #birth rate option
    br = turtle.Turtle()
    br.penup()
    br.showturtle()
    br.goto(-250,150)
    br.shape('br.gif')
    #death rate option
    dr = turtle.Turtle()
    dr.penup()
    dr.showturtle()
    dr.goto(250,150)
    dr.shape('dr.gif')
    #life expectancy option
    le = turtle.Turtle()
    le.penup()
    le.showturtle()
    le.goto(-250,-150)
    le.shape('le.gif')
    #population pyramids (ANIMATED ONE)
    pp = turtle.Turtle()
    pp.penup()
    pp.showturtle()
    pp.goto(250,-150)
    pp.shape('pp.gif')

    #functions for displaying category buttons
    def words(x,y):
        text.clear()
        bg = turtle.Turtle()
        bg.penup()
        bg.showturtle()
        bg.goto(0,0)
        bg.shape('dark.gif')
        word_animation(x,y)
    def birthrate(x,y):
        text.clear()
        bg = turtle.Turtle()
        bg.penup()
        bg.showturtle()
        bg.goto(0,0)
        bg.shape('dark.gif')
        stat = turtle.Turtle()
        stat.penup()
        stat.showturtle()
        stat.goto(0,0)
        stat.shape('birthrates.gif')
        txt = turtle.Turtle()
        txt.pencolor('yellow')
        txt.hideturtle()
        txt.penup()
        txt.goto(0,250)
        txt.write('Click on the dark to go back', False, align="center", font=("Playfair", 20, "normal"))
        bg.onclick(end_dark)
    def deathrate(x,y):
        text.clear()
        bg = turtle.Turtle()
        bg.penup()
        bg.showturtle()
        bg.goto(0,0)
        bg.shape('dark.gif')
        stat = turtle.Turtle()
        stat.penup()
        stat.showturtle()
        stat.goto(0,0)
        stat.shape('deathrate.gif')
        txt = turtle.Turtle()
        txt.pencolor('yellow')
        txt.hideturtle()
        txt.penup()
        txt.goto(0,250)
        txt.write('Click on the dark to go back', False, align="center", font=("Playfair", 20, "normal"))
        bg.onclick(end_dark)
    def lifeexpectancy(x,y):
        text.clear()
        bg = turtle.Turtle()
        bg.penup()
        bg.showturtle()
        bg.goto(0,0)
        bg.shape('dark.gif')
        stat = turtle.Turtle()
        stat.penup()
        stat.showturtle()
        stat.goto(0,0)
        stat.shape('lifeexpectancy.gif')
        txt = turtle.Turtle()
        txt.pencolor('yellow')
        txt.hideturtle()
        txt.penup()
        txt.goto(0,250)
        txt.write('Click on the dark to go back', False, align="center", font=("Playfair", 20, "normal"))
        bg.onclick(end_dark)
    #function if user clicks on 'population pyramid' button
    def pyramid_setup(x,y):

        text.clear()
        #sets background to dark
        bg = turtle.Turtle()
        bg.penup()
        bg.showturtle()
        bg.goto(0,0)
        bg.shape('dark.gif')
        #menu text
        txt = turtle.Turtle()
        txt.pencolor('yellow')
        txt.hideturtle()
        txt.penup()
        txt.goto(0,250)
        txt.write('Click on a country to view its population pyramid', False, align="center", font=("Playfair", 20, "normal"))
        #buttons 
        #china
        china_p = turtle.Turtle()
        china_p.showturtle()
        china_p.goto(0,200)
        china_p.shape('china_button.gif')
        #japan
        japan_p = turtle.Turtle()
        japan_p.showturtle()
        japan_p.goto(0,120)
        japan_p.shape('japan_button.gif')
        #south korea
        korea_p = turtle.Turtle()
        korea_p.showturtle()
        korea_p.goto(0,40)
        korea_p.shape('korea_button.gif')
        #niger
        niger_p = turtle.Turtle()
        niger_p.showturtle()
        niger_p.goto(0,-40)
        niger_p.shape('niger_button.gif')
        #somalia
        somalia_p = turtle.Turtle()
        somalia_p.showturtle()
        somalia_p.goto(0,-120)
        somalia_p.shape('somalia_button.gif')
        #congo
        congo_p = turtle.Turtle()
        congo_p.showturtle()
        congo_p.goto(0,-200)
        congo_p.shape('congo_button.gif')
        #Used to decide where the user clicks
        china_p.onclick(make_pyramid_china)
        japan_p.onclick(make_pyramid_japan)
        korea_p.onclick(make_pyramid_korea)
        niger_p.onclick(make_pyramid_niger)
        somalia_p.onclick(make_pyramid_somalia)
        congo_p.onclick(make_pyramid_congo)

    #if user clicks 'why is this topic important' button
    wo.onclick(words)
    #if user clicks on 'birth rate' button
    br.onclick(birthrate)
    #if user clicks on 'death rate' button
    dr.onclick(deathrate)
    #if user clicks on 'life expectancy' button
    le.onclick(lifeexpectancy)
    #if user clicks on 'population pyramid' button, its take them to animations
    pp.onclick(pyramid_setup)













#MAIN ####################################################################################################
turtle.tracer(False)

# box object for clicking anywhere for starting screen

box = turtle.Turtle()
box.penup()
box.showturtle()
box.goto(0,0)
box.shape('screen.gif')

#text object
text1 = turtle.Turtle()
text1.pencolor('white')
text1.hideturtle()
text1.penup()
text1.goto(0,250)
text1.write('The Population Transformation', False, align="center", font=("Playfair", 30, "normal"))

text2 = turtle.Turtle()
text2.pencolor('yellow')
text2.hideturtle()
text2.penup()
text2.goto(0,150)
text2.write('Click Anywhere to Start', False, align="center", font=("Playfair", 20, "normal"))

# function for what happens if user clicks anywhere on the screeen

def go_back_to_menu(x,y):
    menu()

def startscreenclick(x,y):
    text1.clear()
    text2.clear()
    box.shape('dark.gif')
    menu()        
    
    


box.onclick(startscreenclick) 

turtle.tracer(True)
turtle.mainloop()
